"""create products

Revision ID: d366a47515a7
Revises: 7cd8780ab650
Create Date: 2019-09-27 17:02:33.116042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd366a47515a7'
down_revision = '7cd8780ab650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('license', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'license')
    # ### end Alembic commands ###
